//! End-to-end coverage for `yoink add`'s rendering pipeline against
//! every bundled template in `/templates/`.
//!
//! These tests skip the network: they read the local `templates/`
//! directory directly, mimicking what the source resolver would
//! produce after fetching+extracting the tarball. That keeps the test
//! suite hermetic while still exercising the manifest → wizard →
//! render → validate pipeline.

use std::collections::BTreeMap;
use std::path::PathBuf;

use yoink::add::manifest::TemplateManifest;
use yoink::add::render;
use yoink::add::wizard;
use yoink::config::{Config, ConfigFragment};

fn templates_dir() -> PathBuf {
    // Tests run with cwd = workspace root by default. Resolve from
    // CARGO_MANIFEST_DIR (the yoink/ crate) up one level to the workspace.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace root")
        .join("templates")
}

fn list_template_names() -> Vec<String> {
    let mut names = Vec::new();
    for entry in std::fs::read_dir(templates_dir()).expect("read templates dir") {
        let entry = entry.unwrap();
        if entry.file_type().unwrap().is_dir() && entry.path().join("template.yaml").exists() {
            names.push(entry.file_name().to_string_lossy().into_owned());
        }
    }
    names.sort();
    names
}

fn render_with_defaults(template_name: &str) -> render::Rendered {
    let root = templates_dir().join(template_name);
    let manifest = TemplateManifest::parse_file(&root.join("template.yaml"))
        .unwrap_or_else(|e| panic!("parse {template_name} manifest: {e}"));

    // Use defaults for every variable; require the manifest to declare
    // a default for each (or the test will panic and surface the gap).
    let overrides = BTreeMap::new();
    let vars = wizard::collect_variables(&manifest.variables, &overrides, false)
        .unwrap_or_else(|e| panic!("collect vars for {template_name}: {e}"));

    render::render(&manifest, &root, &vars)
        .unwrap_or_else(|e| panic!("render {template_name}: {e}"))
}

#[test]
fn every_bundled_template_renders_with_defaults() {
    let names = list_template_names();
    assert!(
        !names.is_empty(),
        "no bundled templates found at {}",
        templates_dir().display()
    );
    for name in names {
        let _ = render_with_defaults(&name);
    }
}

#[test]
fn every_rendered_fragment_parses_as_config_fragment() {
    for name in list_template_names() {
        let rendered = render_with_defaults(&name);
        for file in &rendered.files {
            let _: ConfigFragment = yaml_serde::from_str(&file.contents).unwrap_or_else(|e| {
                panic!(
                    "rendered {name} -> {} failed ConfigFragment parse:\n{e}\n--- contents ---\n{}",
                    file.dest.display(),
                    file.contents
                )
            });
        }
    }
}

#[test]
fn every_rendered_fragment_passes_full_config_validation() {
    // Wrap the fragment in a minimal valid Config and run the full
    // validate pipeline. Catches dangling network refs, duplicate
    // service names against the wrapper, etc.
    for name in list_template_names() {
        let rendered = render_with_defaults(&name);
        for file in &rendered.files {
            let combined = wrap_fragment(&file.contents);
            Config::parse_str(&combined).unwrap_or_else(|e| {
                panic!(
                    "rendered {name} -> {} failed full Config validate:\n{e}\n--- combined ---\n{combined}",
                    file.dest.display()
                )
            });
        }
    }
}

#[test]
fn secrets_referenced_in_env_from_secrets_match_generated_names() {
    // Catch typos like `env_from_secrets: { FOO: BARR }` paired with
    // `secrets: [{name: BAR, ...}]`. We can't catch *all* dangling
    // refs (the user's own env_from_secrets might point at a
    // pre-existing key), but for the bundled set we expect every
    // secret a template references in env_from_secrets to be one
    // that the same template generates.
    for name in list_template_names() {
        let rendered = render_with_defaults(&name);
        let generated: std::collections::HashSet<String> =
            rendered.secrets.iter().map(|s| s.name.clone()).collect();
        for file in &rendered.files {
            let frag: ConfigFragment = yaml_serde::from_str(&file.contents).unwrap();
            for svc in &frag.services {
                for secret_key in svc.env_from_secrets.values() {
                    assert!(
                        generated.contains(secret_key) || rendered.secrets.is_empty(),
                        "{name}: service `{}` references secret `{secret_key}` not generated by template ({:?})",
                        svc.name,
                        generated
                    );
                }
            }
        }
    }
}

#[test]
fn templates_directory_matches_index() {
    // index.yaml is the human-curated TL;DR `yoink add` (no args)
    // shows; every dir on disk should be listed there and vice versa,
    // so a new template can't slip in without an index entry (or a
    // dropped template leave behind a dangling listing).
    let dirs = list_template_names();
    let index_text = std::fs::read_to_string(templates_dir().join("index.yaml"))
        .expect("read templates/index.yaml");
    let mut indexed: Vec<String> = index_text
        .lines()
        .filter_map(|l| l.trim().strip_prefix("- name:"))
        .map(|s| s.trim().to_string())
        .collect();
    indexed.sort();
    assert_eq!(
        dirs, indexed,
        "templates/ on disk and index.yaml's `name:` entries diverged"
    );
}

#[test]
fn template_manifests_have_required_fields() {
    for name in list_template_names() {
        let manifest =
            TemplateManifest::parse_file(&templates_dir().join(&name).join("template.yaml"))
                .unwrap();
        assert!(!manifest.name.is_empty(), "{name}: empty name");
        assert!(
            manifest.description.is_some(),
            "{name}: missing description"
        );
        assert!(!manifest.files.is_empty(), "{name}: no files declared");
        // Every variable must have a default (so non-interactive
        // `yoink add <name>` works in CI).
        for var in &manifest.variables {
            assert!(
                var.default.is_some(),
                "{name}: variable `{}` has no default — non-interactive use will fail",
                var.name
            );
        }
    }
}

/// Wrap a fragment in a minimal Config so `Config::parse_str` accepts
/// it. Adds the deploy network the fragment's services declare (if any),
/// plus a host so `validate()` doesn't trip on emptiness.
fn wrap_fragment(fragment_yaml: &str) -> String {
    // Render a fixed wrapper around the fragment's services — we
    // re-deserialize the fragment's services into a plain string by
    // indentation tweaks: the fragment's `services:` already starts at
    // column 0; we just concat after our prelude.
    format!(
        "deploy:\n  networks: [public]\nhosts:\n  - {{ address: testhost, user: deploy }}\n{fragment_yaml}"
    )
}
